
platform :ios, '9.0'
# Uncomment this line if you're using Swift
target 'weiboswift' do
use_frameworks!

pod 'AFNetworking','~>3.0'
pod 'SDWebImage','~>3.7.5'
pod 'SVProgressHUD','~>2.0.2'
pod 'MJRefresh'
pod ‘MJExtension’

end
